### ISSUE TITLE
XeLaTeX doesn't like inputenc

### ISSUE THREAD

**Issue by tobanw** [mlda065/friggeri-letter#1]
XeLaTeX complains (but ultimately allows it) about the use of the `inputenc` package in the template file `example-cover-letter.tex`. I removed that line (#24) and it seems to work fine. The cv example template doesn't use this package, so I'm guessing you didn't intentionally put it in there.

**Comment by mlda065** [comment]
Hmm. Yeah I don't know how that got in there.
It's removed now.
