### ISSUE TITLE
A4 paper size

### ISSUE THREAD

**Issue by gw0** [mlda065/friggeri-letter#5]
> Get rid of magic numbers in the templates, so it works with other paper sizes. (Then again, who doesn't use A4?)

I do not understand this comment from the README.md. The `example-resume.tex` uses US letter paper size (8.5x11 inch or 215.9x279.4 mm). You need to add the option `\documentclass[a4paper]{friggeri-cv}` to use the A4 paper size (8.26389x11.6944 inch or 210x297 mm).

**Comment by mlda065** [comment]
That's referring to the dimensions used to structure the margin of the resume.

```

\xdef\asideHeight{5}

\newcommand\aside[1]{
    \AddEverypageHook{
        \begin{textblock}{3.6}(1.5, \asideHeight) % {width}(xpos,ypos)
            \begin{flushright}
            \linespread{1}\selectfont
            #1
            \end{flushright}
        \end{textblock}
        %
        %all pages aside from the first should have the side bit further up
        %Crude hack to just redefine the y position as we go
        \xdef\asideHeight{2.1}
    }
}
```

5, 3.6, 1.5, 2.1 etc

Those hard coded numbers work with A4. But they may look disproportionate with other paper sizes.

**Comment by gw0** [comment]
That makes more sense. Maybe you could add `a4paper` to `example-resume.tex` to prevent confusion. Otherwise, just close the issue.

**Comment by mlda065** [comment]
Done.

When adding this, I also noticed that the document was broken on my setup, because some library changed. So thank you, now this template is a bit more usable.
